### ISSUE TITLE
Road Events Not Triggering

### ISSUE THREAD

**Issue by prpost98** [jason-whitted/gloomy#1]
When I choose to travel to a scenario, I am not being prompted to complete a Road Event.

- Traveling from Gloomhaven
- Selecting to Travel to Scenario... (NOT the casual mode)

Is there an alternate way to track resolved road events?

**Comment by jason-whitted** [comment]
@prpost98 Good catch!  Road events were not properly triggering when traveling in campaign mode.  This has been fixed.
