### ISSUE TITLE
Can't delete, create, or import scenario

### ISSUE THREAD

**Issue by SoccerCore11** [jason-whitted/gloomy#10]
I get the following error:
Unable to get configuration.
JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4 of the JSON data

How do I do a complete reset?

**Comment by jason-whitted** [comment]
All of the Gloomy data is stored in your Github gists.  You could go delete all of the gloomy-related gists to do a hard reset.

- Go to [https://gist.github.com/SoccerCore11](https://gist.github.com/SoccerCore11)
- Click on each `Gloomy Campaign` or `Gloomy Configuration`
- Click [Delete]

Once they are all deleted, you should be able to return to Gloomy and everything should be reset.

**Comment by jason-whitted** [comment]
@SoccerCore11 I'm going to close this issue.  If you have any further questions on this, let me know.
