### ISSUE TITLE
Number of perks are off

### ISSUE THREAD

**Issue by OregonPinkRose** [jason-whitted/gloomy#27]
It appears that the number of perks are off when building an existing campaign.
I have 1 retired characters and all my existing characters have 1 more perk than necessary and I can only figure it's from the retired character.

Inputting them in before I decided to enter my existing campaign had them turn out fine, so I know it's not a rules issue.

**Comment by jason-whitted** [comment]
I’m having to override the calculations for bonus perks when importing from the builder. I must’ve screwed up somewhere. I’ll look into it this evening. 

Could you provide the build code you were using?

**Comment by jason-whitted** [comment]
This has been fixed in 0.1.10.
