### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by OregonPinkRose** [jason-whitted/gloomy#33]
Without giving anything more away, We need to be able to keep tracking how much is donated to the Great Oak beyond 100 gold.

It might be because I already donated with all of my characters already this trip to town.
If so, please disregard. I'll update when I can next update if necessary.

**Comment by jason-whitted** [comment]
Sanctuary Donations are displayed on the main campaign page.  When in Gloomhaven each character may donate once to the sanctuary if the last scenario completed was not done in casual mode.  On the character sheet Gloomy will even put a :star: next to your gold with a note reminding you that a donation is available.

PS - Envelope B is tracked and the bonus prosperity is automatically awarded to the campaign.

**Comment by SoccerCore11** [comment]
After retiring and creating a new character, the new character should be able to donate right? Doesn't seem like the logic currently allows this.

**Comment by jason-whitted** [comment]
> **How are sanctuary donations, road and city events handled when playing scenarios in casual mode?**

> Sanctuary donations and city events can only be done if the last scenario played was in campaign mode. Road events can only be done if the next scenario is being played in campaign mode.

The new character has not completed any scenarios. Unless there is some documentation stating otherwise from Isaac, I believe it is working as intended.

**Comment by SoccerCore11** [comment]
Seems you might be right because of the wording of 'player' vs 'character'.
From the rulebook p45:

> DONATING TO THE SANCTUARY
> Once per visit to Gloomhaven, each player can donate 10 gold to the Sanctuary of the Great Oak, a temple and hospital in the city. Doing so allows the donating player to add two BLESS attack modifier cards to their attack modifier deck for the next scenario.
