### ISSUE TITLE
1 Click

### ISSUE THREAD

**Issue by OregonPinkRose** [jason-whitted/gloomy#34]
Is there a reason that menus that only have 1 option open a second menu to select that one option?
If I select a character, it opens up a menu that says go to that character page.
If that's the only option, why does it give me that option? WHy not just go to that character page?
It would save a bunch of clicks if there is no reason for doing it the way you did it.

**Comment by jason-whitted** [comment]
Some menu items are hidden based on permissions, or current campaign conditions -- if I just invoked the menu item when there is only one available it could mean that it behaves differently depending on what state the campaign is currently in.  That's a bad UX.

Currently the UX is consistent.  Gloomy is growing and as more features are added, more items could appear in the flyouts.
