### ISSUE TITLE
Global achievement issue (spoiler of scenario 46, 47, 48, 51)

### ISSUE THREAD

**Issue by langerest** [jason-whitted/gloomy#35]
Our party completed scenario 47 and 48 but only one End of Corruption achievement is given. 
(There should be 3 End of Corruption achievement obtained from completing scenario 46, 47, 48, respectively, and scenario 51 requires all 3 of them).

**Comment by jason-whitted** [comment]
This *should* be fixed in 0.1.12.  If it is not, let me know and I'll reopen this issue.

**Comment by langerest** [comment]
It's fixed. Thank you!
