### ISSUE TITLE
Solo Scenario Item Issue

### ISSUE THREAD

**Issue by langerest** [jason-whitted/gloomy#39]
We had a music note character, who completed the solo scenario, got the item and then retired. The item should go to the shop. (These are imported through campaign builder).

Now our second music note character wants to buy that item, but it's not on the list.

**Comment by jason-whitted** [comment]
Hm. This should be working already. 

Was the first character retired using the campaign builder or from within the gloomy campaign?  
If retired from within the Gloomy campaign, were the characters items sold before retiring?

**Comment by langerest** [comment]
It was retired in the builder.

**Comment by jason-whitted** [comment]
Fixed in 0.1.13

**Comment by langerest** [comment]
I still can't find the item in the list

**Comment by jason-whitted** [comment]
You will need to recreate the campaign. The problem was during the import process.
