### ISSUE TITLE
Retirement-Eligible Character Can't donate to sanctuary

### ISSUE THREAD

**Issue by prpost98** [jason-whitted/gloomy#4]
I have a character that just finished their personal quest. In Gloomhaven, I see the option to retire. However, this character still has a bit of gold and even though it's a waste (no blessing benefit), I want to advance progress toward the envelope opening and donate 10g to the sanctuary. That options isn't available to me though.

**Comment by jason-whitted** [comment]
Gloomy was incorrectly preventing sanctuary donations if the previous scenario was failed.  This has been fixed.  Thanks for the report, @prpost98.
