### ISSUE TITLE
Error when selecting campaign.

### ISSUE THREAD

**Issue by TacoSupreme** [jason-whitted/gloomy#42]
After finishing scenario 22 we marked it as finished and entered in all our xp/gold/checks.   When the last character was finished it gave us this error.

https://imgur.com/zczx2dR

We now get the error each time we select our campaign.  For now I went back to recording it on paper, but would love to find a way to recover all our information from the website.

**Comment by jason-whitted** [comment]
Fixed in 0.1.15.  Sorry for the inconvenience!
