### ISSUE TITLE
Elemental Samples Personal Quest

### ISSUE THREAD

**Issue by TacoSupreme** [jason-whitted/gloomy#44]
Scenario 19 doesn't seem to count as a lingering swamp quest, however according to the FAQ it should.

https://rpggeek.com/wiki/page/thing%3A174430%3AOfficial_FAQ#toc8

It seems that you have it marked as a crypt for the other personal quest that needs that instead.  It should count as both.

**Comment by jason-whitted** [comment]
This should be fixed in 0.1.16.  I had to change the region classification for crypt scenarios.  It should automatically resolve itself after your refresh your campaign.  If it does not, let me know -- we **_may_** have to do a manual update to your campaign's gist.
