### ISSUE TITLE
+1 Range enhancement is 30g, not 50g

### ISSUE THREAD

**Issue by SoccerCore11** [jason-whitted/gloomy#45]
References:
- https://www.reddit.com/r/Gloomhaven/comments/89lrwp/created_5_x_7_reference_cards_to_slip_into_my/
- http://thearcane.li/utilities/enhancementCalculator

**Comment by SoccerCore11** [comment]
On the Doomstalker card "Sap Life", the +1 Range cost is showing as 100g, should be 30g.

**Comment by jason-whitted** [comment]
Fixed in 0.1.17
