### ISSUE TITLE
Store items not added when increasing city prosperity level

### ISSUE THREAD

**Issue by SoccerCore11** [jason-whitted/gloomy#47]
Our city prosperity level just increased to level 4 and is shown correctly, but no new items were added as available to buy from the store.

**Comment by jason-whitted** [comment]
I can't reproduce this.  In a test campaign I had 10 prosperity.  I added 5 prosperity to bump it to Prosperity Level 4, and the items showed up for purchase immediately.  Is this still a problem for you?  If not, it may have been a caching issue.

**Comment by SoccerCore11** [comment]
cf97b21b6bdfe90035c740a1bf3b2c83

Maybe this ID will help troubleshoot?

**Comment by jason-whitted** [comment]
It absolutely did!  Thank you.  This is fixed in 0.1.20
