### ISSUE TITLE
Limit of enhanced cards incorrect

### ISSUE THREAD

**Issue by dhdasilva** [jason-whitted/gloomy#48]
After I augment two actions of the same card, the augment link is gone, despite the prosperity of Gloomhaven being 2.

Based in some tests that I've done, seems that Gloomy is limiting the number of **actions** in the same deck, instead of **cards**.

> Additional costs are added based on the level of the ability card and the number of previously placed enhancement stickers on the same **action**.
> The total number of enhanced cards in a class’s ability deck must be **equal to or less than** the prosperity level of the town.

Rulebook, page 46.

**Comment by jason-whitted** [comment]
Great catch.  Thanks for the research and corresponding documentation.  This has been fixed in 0.1.18.
