### ISSUE TITLE
Spoilers in issues

### ISSUE THREAD

**Issue by dhdasilva** [jason-whitted/gloomy#49]
What do you think about add some guide in the main README.MD so people submitting new issues could avoid spoilers for others?

I imagine something simple like "avoid classes names (use "sun class", for example), refer to items, events and scenarios by its numbers".

I'm loving Gloomy and really want to clone and help you with some PRs, but I'm very afraid of get spoilers either. Tough decision hahaha.

**Comment by jason-whitted** [comment]
People have been pretty good about spoilers.  Frankly, it's going to be hard to provide me enough information to fix an issue without providing spoiler details.  The title's should be spoiler free but the issue details do not need to be spoiler free.  If someone is really wanting to avoid spoilers they should not read all of the existing issues.
