### ISSUE TITLE
Stuck on Creating Players with Campaign Builder

### ISSUE THREAD

**Issue by langerest** [jason-whitted/gloomy#5]

**Comment by jason-whitted** [comment]
@langerest  In order to help debug this I'll need your build code.

**Comment by langerest** [comment]
eyJwbGF5ZXJzIjpbIkthaWxpIiwiU3RldmUiLCJBbGV4xAd1c3RpbsQYaGFyZWQiXSwicGFydGllxTVFdmV0c8QUY2xhc3PEFHsiQlIiOnRydWUsIkNIyApNVMgKU0PJClfIClRJyApCRcgKRFPICk7JClNLyQrKFFXGCn0sImNoYXJhY3TmANDoANwiOjHmALJ5Ijow5wCoIjrEfSwibmFtZSI6IlRlbXBlc3QiLCJsZXZlbCI6OSwicXXEEjo1MjksInJldGnkAPvHcmJvbnVzUGVya3MiOjB9LMppMtVpQ8ppTW9ycmHKZzjLZzLfZ8tnMNRnTVTKZ0knbGwgc3RlYWwgeW91ciBoZWFy9gDeM993zHc01HdUScp3U3dpZnR3actqNcpqMjffastqM9RqQ0jKakFsaXphcuUCltNqMd9q/wFL5AJcyWpSaW5nIGFyb3VuZCB0aGUgcm9zaeQDHfMBSzDfd/8CKeQC58l3SGF3a3dvb2TWajPLamZhbHPPazHfazrkA0jJa0x1Y2VybusCljfKajI432rMavUDZ0TrANVKZWZm9gL9Nd9n/wKHOuQEN8lnQ2hhcmxvdHTrAac2ymwz7AIe32z3Ah9VymxUaGUgbGVnZW5kIG9mIGZpdmUgcmluZ3PVezI03nsyfeQFSGl0eUV2ZW505ATEMSwyLDcsMTAsMTMsMTgsMjMsMjQsMzEsMzMsMzQsNDMsNDQsNDUsNTQsNzAsNzEsNzMsNzVdLCJyb2FkzUUzLDQsNiw4LDksMTLFTTQsMTUsMTcsMjUsMjnKUzM2xVM2xFM2Nl0sInNjZW5hcmlv5QXZMeQBXm9tcGxl5QFdMs4PM84PNM4PNc4PNs4PN84POM4POeQD83ZhaWxhYmzEEDEwziAxz3sxz3wxxH3NQc9/Me8AgDHkAIHNMeQAg8shMu8AgjLkARvMMTLvAR0y7wCTMu8BEDLkAILNQe8BBDLvAIIz7wCCM+8BnTPwAZ7vASQz5ACRzHEz8AElM+QBJc0R8ACkM/ABJzPvAKU07wClNO8ApTTkAKXMQTTwAkXwAIQ17wE4Ne8ByjbPYjbvAQc2xGHMUTbPUTbvAMM37wDDN/AAszfwAKM48AIMONAzOPABSTnvAPfkCN7KEH0sImdsb2JhbEFjaGlldmVt5gPZ5QOQM+UDeDHlAzMx5gMKxAc0xgc1xgc2xgfGI+QCuzF95wTZ01IxyFLGRMY8zl430VDmAwLEBzLGB8QqfSwiZW52ZWxvcOcKGOkJqWl0ZW3kBJs3NeUEluYE4Tg3LDIwLDIx5QTnxBUw5QSYNCwzNSwzNywzOCw0MuQE9DEyxAQ0LDXkBOpkb25hdGlvbnMiOjU1fQ==

**Comment by langerest** [comment]
Seems like this is system related issue as it stuck on ubuntu with chrome but worked correctly on my iPhone

**Comment by jason-whitted** [comment]
Yeah, could be.  I just tried it on my mac and it worked.  You should be good to go once it is created though.
