### ISSUE TITLE
Feature Request - Show a summary of campaign 

### ISSUE THREAD

**Issue by Murteas** [jason-whitted/gloomy#51]
It would be very nice to have at a glance a summary of the campaign status - i.e. All scenarios available, completed.  Treasures looted, still available, items unlocked, etc.   Just make it easier to see at a glance.

**Comment by jason-whitted** [comment]
I added a Scenario list to the campaign page that lists Available and Completed scenarios.  This is available in 0.1.21.

Gloomy doesn't currently track which scenarios have had their treasure looted.  I created an enhancement for that.
