### ISSUE TITLE
The bottom of Scoundrel Ability Card "Backstab" not matching physical card

### ISSUE THREAD

**Issue by brokirk** [jason-whitted/gloomy#72]
In gloomy/src/constants/ABILITY_CARD/CONFIG/Scoundrel/index.js the bottom of Ability Card "Backstab" currently shows ATTACK 6.  The physical card shows MOVE 6.

P.S. I otherwise love this site.  It's making our remote game doable.

**Comment by icosahedron** [comment]
I created a PR for this.

**Comment by jason-whitted** [comment]
This has been merged and pushed. Thanks for the PR, @icosahedron!
