### ISSUE TITLE
Personal quest 510 completing too early

### ISSUE THREAD

**Issue by Fraxinus1753** [jason-whitted/gloomy#74]
Hi Jason, the personal quest 510 (Seeker of Xorn) normally requires you to complete three crypt scenarios, then unlock and complete scenarios 52, 53 and 54 in that order. However, Gloomy forces us to retire the character after completing scenario 52 only, with no possibility to override that. 

Thanks again for this absolutely amazing tool!

**Comment by jason-whitted** [comment]
This should be fixed in 0.1.28.
