### ISSUE TITLE
Cannot change personal quest OR delete characters

### ISSUE THREAD

**Issue by Ramadel** [jason-whitted/gloomy#79]
I mis-assigned a character's personal quest. It doesn't let me change it, and I see you can't delete a character. Am I just permanently stuck? I'm definitely not going through the effort of recreating ALL of the campaign events.

**Comment by jason-whitted** [comment]
@Ramadel,

There's two options for corrections.
1. You can see if the action is reversable in the History section on your main campaign screen.  You can click the Delete button and undo a change.
2. You can manually find and modify/remove the entry from the campaign.  You can do this by navigating to https://gist.github.com and you should see your campaign listed there.
  * Within the campaign you can modify the `gloomy.campaign.js` file directly.
  * Please note that with this approach you may risk corrupting your campaign file.  I *highly* recommend you make a backup of the file before you try making any changes.
  * But you can find the line containing the action that you wish to modify and change it.
  * I provide no support for these modifications.  You may need to search through the source code for specific IDs, etc.

Good luck.  Hopefully one of these options helps resolve your issue.
