### ISSUE TITLE
Error when travel to a new scenario with imported campaign

### ISSUE THREAD

**Issue by langerest** [jason-whitted/gloomy#9]
The following screen pops up:

🐛 ¯\_(ツ)_/¯
"I've got good news and bad news."

Some dude
Bad News:
This site was hacked together with much haste by a terrible programmer. As was to be expected we've encountered a totally unexpected error.

Good News:
I just saved a bunch of money by switching to Geico©!

You can try clicking this  to hard-refresh everything.

**Comment by jason-whitted** [comment]
Thanks for reporting the issue.  This has been fixed in the latest version (0.1.8).
